import type { Metadata } from 'next';
import { Orbitron, Rajdhani, Fira_Code } from 'next/font/google';
import '@styles/globals.css';

const fontSans = Orbitron({
    subsets: ['latin'],
    variable: '--font-sans',
});

const fontSerif = Rajdhani({
    subsets: ['latin'],
    weight: ['300', '400', '700'],
    variable: '--font-serif',
});

const fontMono = Fira_Code({
    subsets: ['latin'],
    variable: '--font-mono',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} antialiased`}
            >
                <div className="js-page page">{children}</div>
            </body>
        </html>
    );
}
